spring:
#  aop:
#    auto: true
#    proxy-target-class: true

mail:
  host: ${mail_host:smtp.gmail.com}
  port: ${mail_port:587}
  protocol: smtp
  default-encoding: UTF-8
  smtp:
    start-tls-enable: true
    auth: true
  username: ${mail_username}
  password: ${mail_password}
  email-voyagerss: ${mail_sender:voyagerss@gmail.com}

file:
  upload-dir: /ftp

core:
  web-address: ${VITE_WEB_URL:https://localhost:3003}


---
spring.config.activate.on-profile: local
spring.devtools.livereload.enabled: true

---
spring.config.activate.on-profile: develop
---
spring.config.activate.on-profile: release
