spring:
#  aop:
#    auto: true
#    proxy-target-class: true

mail:
  host: smtp.gmail.com
  port: 587
  protocol: smtp
  default-encoding: UTF-8
  smtp:
    start-tls-enable: true
    auth: true
  username: ${mail_username}
  password: ${mail_password}
  email-voyagerss: voyagerss@gmail.com
  email-manager: abigailmaureen1993@gmail.com

file:
  upload-dir: /ftp


---
spring.config.activate.on-profile: local
core:
  web-address: https://localhost:3003

spring:
  devtools:
    livereload:
      enabled: true


---
spring.config.activate.on-profile: develop
core:
  web-address: https://dev.en9doors.com

---
spring.config.activate.on-profile: release
core:
  web-address: https://en9doors.com

---
spring.config.activate.on-profile: release-voyagerss
core:
  web-address: https://voyagerss.com