management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,threaddump,heapdump
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    group:
      readiness:
        include: db,diskSpace
      liveness:
        include: ping 