name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'workschd-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup GCP CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: voyagerss
          
      - name: Build and Deploy
        run: |
          cd workschd-api
          ./gradlew bootBuildImage
          docker tag app gcr.io/voyagerss/api
          docker push gcr.io/voyagerss/api
          gcloud run deploy api \
            --image gcr.io/voyagerss/api \
            --platform managed \
            --region asia-northeast3 \
            --allow-unauthenticated \
            --ingress internal-and-cloud-load-balancing 